// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiDdd.Infrastructure.Data;

#nullable disable

namespace RestApiDdd.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestApiDdd.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("Expire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FullPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsQuantityAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PackageCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("PostPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PackageCategoryId");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.PackageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PackageCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Share Plan",
                            SortOrder = 1,
                            Visible = false
                        },
                        new
                        {
                            Id = 2,
                            Name = "Default",
                            SortOrder = 2,
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Billing Activation",
                            SortOrder = 3,
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Share Plan Add-on",
                            SortOrder = 4,
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "One Time Billing",
                            SortOrder = 5,
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Global Add-on",
                            SortOrder = 6,
                            Visible = false
                        });
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.PackageFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "Name")
                        .IsUnique();

                    b.ToTable("PackageFrequency", (string)null);
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.PackageService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultInstances")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumInstances")
                        .HasColumnType("int");

                    b.Property<int>("MinimumInstances")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("PackageId", "ServiceId")
                        .IsUnique();

                    b.ToTable("PackageService", (string)null);
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Service", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default seeded service value.",
                            Name = "Core Service"
                        });
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.Package", b =>
                {
                    b.HasOne("RestApiDdd.Domain.Entities.PackageCategory", "PackageCategory")
                        .WithMany()
                        .HasForeignKey("PackageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PackageCategory");
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.PackageFrequency", b =>
                {
                    b.HasOne("RestApiDdd.Domain.Entities.Package", "Package")
                        .WithMany("Frequencies")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.PackageService", b =>
                {
                    b.HasOne("RestApiDdd.Domain.Entities.Package", "Package")
                        .WithMany("Services")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestApiDdd.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("RestApiDdd.Domain.Entities.Package", b =>
                {
                    b.Navigation("Frequencies");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
